version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "10080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
  app1:
    image: myflaskapp
    container_name: app1
    ports:
      - "5001:5000"
  app2:
    image: myflaskapp
    container_name: app2
    ports:
      - "5002:5000"
  app3:
    image: myflaskapp
    container_name: app3
    ports:
      - "5003:5000"
